[package]
name = "letterbox-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "letterbox_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = "1.0"

[dev-dependencies]
once_cell = "1.19"
